version: "3"
services:
  webserver:
    image: php:7.2-apache
    restart: always
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    